### ISSUE TITLE
Exception: Template format error: Unrecognized resource types: [AWS::Serverless::Function] (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError;

### ISSUE THREAD

**Issue by gvasquez95** [jenkinsci/aws-sam-plugin#4]
Seems to me that the latest plugin version is not entirely supporting all resource types, specifically `AWS::Serverless::Function`, as it's rejecting this template which does deploy correctly from the Eclipse AWS Toolkit using SAM CLI:

`{
  "Description" : "Integracion",
  "Resources" : {
    "GetFlotaRole" : {
      "Type" : "AWS::IAM::Role",
      "Properties" : {
        "AssumeRolePolicyDocument" : {
          "Version" : "2012-10-17",
          "Statement" : [ {
            "Effect" : "Allow",
            "Principal" : {
              "Service" : "lambda.amazonaws.com"
            },
            "Action" : "sts:AssumeRole"
          } ]
        },
        "ManagedPolicyArns" : [ "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole", "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole" ],
        "Path" : "/integraciones/avis/geoxite/",
        "RoleName" : "GetFlotaRole"
      }
    },
    "GetFlota" : {
      "Type" : "AWS::Serverless::Function",
      "Properties" : {
        "Handler" : "com.company.Class",
        "Runtime" : "java8",
        "CodeUri" : "./target/myArtifact-1.0.0.jar",
        "MemorySize" : "256",
        "Timeout" : "5",
        "VpcConfig" : {
          "SecurityGroupIds" : [ "sg-yyyyyy" ],
          "SubnetIds" : [ "subnet-xxxxxxxxx", "subnet-zzzzz" ]
        },
        "Role" : {
          "Fn::GetAtt" : [ "GetFlotaRole", "Arn" ]
        },
        "Events" : {
          "GetResource" : {
            "Type" : "Api",
            "Properties" : {
              "Path" : "/flota",
              "Method" : "get"
            }
          }
        }
      }
    }
  }
}`

Jenkins ver. 2.150
AWS SAM plugin 1.2.2
Amazon Web Services SDK plugin 1.11.403

Stacktrace:

`com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Template format error: Unrecognized resource types: [AWS::Serverless::Function] (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: c86c43be-ffd7-11e8-babc-b1d2e9c4fe98)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1658)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1322)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:2931)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:2900)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:2889)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeValidateTemplate(AmazonCloudFormationClient.java:2855)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.validateTemplate(AmazonCloudFormationClient.java:2826)
	at com.amazonaws.jenkins.plugins.sam.service.CloudFormationService.validateTemplate(CloudFormationService.java:49)
	at com.amazonaws.jenkins.plugins.sam.DeployBuildStep.perform(DeployBuildStep.java:70)`

**Comment by bigunyak** [comment]
Make sure you have the following header in your template. `cfnUpdate` works for me with `AWS::Serverless::Api` resource in the template.
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
```

**Comment by chukkalapradeep** [comment]
> Make sure you have the following header in your template. `cfnUpdate` works for me with `AWS::Serverless::Api` resource in the template.
> 
> ```
> AWSTemplateFormatVersion: '2010-09-09'
> Transform: 'AWS::Serverless-2016-10-31'
> ```

Is this issue resolved. Were you able to deploy  AWS::Serverless::Function.

**Comment by bac-dam-1991** [comment]
Hi @gvasquez95 ,

I had the same problem and after following @bigunyak 's solution the CF Template deployed properly again. Good luck.

**Comment by brainstorm** [comment]
The `Transform: AWS::Serverless-2016-10-31` on my `template.yml` was enough to get this deployed for me, no need for the `AWSTemplateFormatVersion: '2010-09-09'` bit... 🤷🏻‍♂️
